# Generated by Django 4.1 on 2022-10-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="password",
            new_name="password_hash",
        ),
    ]
