# Generated by Django 4.1 on 2022-10-17 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_rename_password_user_password_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                max_length=255, validators=[django.core.validators.MinValueValidator(8)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=255, validators=[django.core.validators.EmailValidator]
            ),
        ),
    ]
