# Generated by Django 4.1 on 2022-10-26 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_usersanswers_rename_text_answers_answer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answers",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="usersanswers",
            old_name="answer_id",
            new_name="answer",
        ),
        migrations.RenameField(
            model_name="usersanswers",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="usersanswers",
            old_name="user_id",
            new_name="user",
        ),
    ]
